---
# This playbook contains common plays that will be run on all nodes.

- name: synergy | shell | Check user
  user: name={{ synergy_owner }} state={{ synergy_user_state }}

- name: synergy | shell | Check user home directory
  stat: path={{ synergy_owner_home }}
  register: home_present

- debug: msg=" shell | Path exists and is a directory"
  when: home_present.stat.isdir is defined and home_present.stat.isdir == true

- name: synergy | Create temporary directory
  shell: mktemp -d
  register: tempdir
  become: yes
  tags: synergy_setup

- name: synergy | Download synergy
  get_url:
    url="{{ synergy_url }}"
    dest="{{ synergy_dir_tmp }}/{{ synergy_archive }}"
  become: yes
  register: synergy_download
  tags: synergy_setup
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )

#- name: synergy | Create base directory
#  file:
#    dest="{{synergy_base_dir}}/{{synergy_name}}"
#    state=directory
#    owner="{{synergy_owner}}"
#    group="{{synergy_group}}"
#  when: synergy_download.changed
#  tags: synergy_setup
#  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )

- name: synergy | Add synergy repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
  ignore_errors: true
  tags: synergy_setup

#- name: synergy | Alternative | Add synergy repository key
#  shell: curl -sSL https://symless.com/gpg | sudo apt-key add -
#  when: add_repository_key|failed

- name: synergy | Add package
  apt: deb={{ synergy_dir_tmp }}/{{ synergy_package_deb }}
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
#  when: synergy_download.changed
  become: yes
#  ignore_errors: true
  tags: synergy_setup

#- name: synergy | Change archive synergy ownership
#  file: path={{synergy_base_dir}}/{{synergy_name}} owner={{synergy_owner}} group={{synergy_group}} state=directory recurse=yes
#  when: synergy_download.changed
#  tags: synergy_setup
#
#- name: synergy | Stat {{synergy_base_dir}}/{{synergy_name}}
#  stat: path={{synergy_base_dir}}/{{synergy_name}}
#  register: synergy_archive_extracted_present
#  tags: synergy_setup
#
#- debug: msg=" synergy | Path exists and is a directory"
#  when: synergy_archive_extracted_present.stat.isdir is defined and synergy_archive_extracted_present.stat.isdir == true
#  tags: synergy_setup
#
#- fail: msg=" synergy | Whoops! file ownership has changed"
#  when: synergy_archive_extracted_present.stat.pw_name != '{{synergy_owner}}'
#  tags: synergy_setup
#
#- name: synergy | Create a link to synergy (1)
#  file:
#    src="{{synergy_base_dir}}/{{synergy_name}}"
#    dest="{{synergy_base_dir}}/synergy-{{synergy_major}}"
#    state=link
#    owner="{{synergy_owner}}"
#    group="{{synergy_group}}"
#  tags: synergy_setup
#
#- name: synergy | Create a link to synergy (2)
#  file:
#    src="{{synergy_base_dir}}/{{synergy_name}}"
#    dest="{{synergy_link_base_dir}}/synergy-{{synergy_major}}"
#    state=link
#    owner="{{synergy_owner}}"
#    group="{{synergy_group}}"
#  tags: synergy_setup

- name: synergy | Configure server
  template: src=synergy.conf.j2 dest={{ synergy_owner_home}}/{{ synergy_configuration }} mode=0755
  become: yes
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
  tags: synergy_setup

#https://help.ubuntu.com/community/SynergyHowto
#Add client to startup
#- name: synergy | Autostart Synergy before logging in (LightDM) | Update client
#  lineinfile:
#    dest=/etc/lightdm/lightdm.conf
#    line="greeter-setup-script=/usr/bin/synergyc {{ synergy_server }}"
#    regexp="^greeter-setup-script"
#    state=present
#    insertafter=EOF
#  become: yes
#  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
#  tags: synergy_setup

#Below crash lightdm
#- name: synergy | Autostart Synergy before logging in (LightDM) | Update server
#  lineinfile:
#    dest=/usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
#    line="greeter-setup-script=/usr/bin/synergys -c {{ synergy_server }}"
#    regexp="^greeter-setup-script"
#    state=present
#    insertafter=EOF
#  become: yes
#  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
#  tags: synergy_setup

- name: synergy | Cleanup temporary directory
  file: name={{ tempdir.stdout }} state=absent
  tags: synergy_setup
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
